---
title: "Verkenning macro-invertebraten meetplaatsen meetnet VMM in kader van MAP"
author: "Hans Van Calster"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
renv::restore()

# set up
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  out.width = "100%")
opts_knit$set(root.dir = here::here())

# packages
library(tidyverse)
library(sf)
library(mapview)
library(readxl)
conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::select)
```

# Inlezen data

```{r mapdata}
sheetnames <- excel_sheets(here("data", "vmm", "macroinvertebratenMAP.xlsx"))

vmm_map <- lapply(sheetnames[1:5], read_excel,
       path = here("data", "vmm", "macroinvertebratenMAP.xlsx"))

vmm_map <- setNames(vmm_map, sheetnames[1:5] %>% janitor::make_clean_names())
vmm_map <- lapply(vmm_map, janitor::clean_names)
```

```{r}
vmm_meetnet <- vmm_map$bbi_en_mmif_deelmaatlatten %>%
  select(meetplaats, jaar, bbi) %>%
  arrange(meetplaats, jaar) %>%
  left_join(
    vmm_map$meetplaatsen %>%
      select(meetplaats, x, y, waterlichaam, bekken, waterloop, categorie),
    by = "meetplaats") %>%
  st_as_sf(coords = c("x", "y"), crs = 31370) %>%
  mutate(jaar = parse_number(jaar),
         bbi = parse_number(bbi))
```

# Verkenning

```{r}
vmm_meetnet %>%
  ggplot() + 
  geom_line(aes(x = jaar, y = bbi, group = meetplaats)) +
  facet_wrap(~bekken)
```

```{r}
vmm_meetnet %>%
  select(jaar, meetplaats, bekken) %>%
  group_by(bekken) %>%
  mutate(meetplaats = reorder(meetplaats, jaar, length)) %>%
  ggplot() +
  geom_point(aes(x = jaar, y = meetplaats, colour = bekken))
```


```{r}
vmm_meetnet %>%
  st_drop_geometry() %>%
  group_by(bekken, meetplaats) %>%
  summarise(aantal_bemonsteringen = n(),
            start_jaar = min(jaar),
            eind_jaar = max(jaar),
            .groups = "drop_last") %>%
  summarise(aantal_meetplaatsen = n_distinct(meetplaats),
            gemiddeld_aantal_bemonsteringen = mean(aantal_bemonsteringen),
            gemiddelde_periode = mean(eind_jaar - start_jaar)) %>%
  kable(digits = 1)
```

```{r}
vmm_meetnet %>%
  st_drop_geometry() %>%
  count(bekken, jaar) %>%
  arrange(jaar) %>%
  pivot_wider(id_cols = c(bekken), names_from = jaar, values_from = n,
              values_fill = 0) %>%
  kable(caption = "aantal bemonsterde meetplaatsen", format = "simple")
```

```{r}
mapviewdata <- vmm_meetnet %>%
  group_by(bekken, meetplaats) %>%
  summarize(jaren = paste(jaar, collapse = ", "),
            lengte_reeks = max(jaar) - min(jaar),
            aantal_bemonsteringen = n(),
            recentste_jaar = max(jaar),
            .groups = "drop")

mapviewdata %>%
  mapview(zcol = "bekken")

mapviewdata %>%
  mapview(zcol = "lengte_reeks")

mapviewdata %>%
  mapview(zcol = "aantal_bemonsteringen")

mapviewdata %>%
  mapview(zcol = "recentste_jaar")
```

# Subset data

- recente data beschikbaar (>= 2015)
- >= 10 jaar tussen eerste en laatste bemonstering
- >= 4 bemonsteringen

```{r}
mapviewdata %>%
  filter(recentste_jaar >= 2015,
         lengte_reeks >= 10,
         aantal_bemonsteringen >= 4) %>%
  mapview()
```

```{r}
mapviewdata %>%
  filter(recentste_jaar >= 2015,
         lengte_reeks >= 10,
         aantal_bemonsteringen >= 4) %>%
  st_drop_geometry() %>%
  select(-recentste_jaar) %>%
  count(bekken)
```

