---
title: "Invloed van beheerovereenkomsten op akkervogels"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
bibliography: references.json
---

```{r setup, include=FALSE}
# renv
renv::restore()

# Set up
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE)
opts_knit$set(root.dir = here())

# Conflicting packages
conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::select)
conflicted::conflicts_prefer(dplyr::lag)
conflicted::conflicts_prefer(brms::ar)
conflicted::conflicts_prefer(brms::do_call)

# Packages
library(tidyverse)
library(INBOtheme)
library(sf)
library(brms)
```

# Inlezen data

```{r}
data_path <- here("data", "processed")
mas_data_df <- read_csv(here(data_path, "MAS_data_full_2018_2022.csv"))

```

```{r}
design <- mas_data_df %>%
  distinct(plotnaam, regio, periode_in_jaar, jaar)

mas_data_sf <- st_as_sf(mas_data_df, coords = c("x_lambert", "y_lambert"), 
                        crs = 31370)

perimeters <- read_sf(
  here("data", "processed", "piloot_perimeters.gpkg"))
```


# Dataset structuur

Hoe ziet de dataset eruit?

```{r}
glimpse(mas_data_df)
```

We visualiseren ook de waarnemingen en kleuren hoeveel jaren het telpunt geteld is.

```{r}
visits_per_jaar <- mas_data_sf %>%
  st_drop_geometry() %>%
  group_by(plotnaam) %>%
  mutate(n_per_jaar = n_distinct(jaar)) %>%
  ungroup() %>%
  select(plotnaam, n_per_jaar) %>%
  distinct()

mas_data_sf %>%
  filter(regio == "De Moeren") %>%
  left_join(visits_per_jaar, by = join_by(plotnaam)) %>%
  ggplot() +
    geom_sf(data = perimeters %>% filter(Naam == "De Moeren"), 
            colour = "firebrick") +
    geom_sf(aes(colour = factor(n_per_jaar)), size = 0.5) +
    labs(title = "De Moeren", colour = "aantal jaren\ntelpunt geteld") +
    guides(colour = guide_legend(override.aes = list(size = 3)))
```

```{r}
mas_data_sf %>%
  filter(regio == "Oostelijke leemstreek") %>%
  left_join(visits_per_jaar, by = join_by(plotnaam)) %>%
  ggplot() +
    geom_sf(data = perimeters %>% filter(Naam == "Oostelijke leemstreek"), 
            colour = "firebrick") +
    geom_sf(aes(colour = factor(n_per_jaar)), size = 0.5) +
    labs(title = "Oostelijke leemstreek", 
         colour = "aantal jaren\ntelpunt geteld") +
    guides(colour = guide_legend(override.aes = list(size = 3)))
```

# Model specificatie test: Gele kwikstaart

We selecteren de data van de Gele kwikstaart met broedcode > 0. We sommeren de aantal per telcirkel, telperiode en jaar. We voegen ook afwezigheden toe.

```{r}
# Presence data
gele_kwik_presences <- mas_data_df %>%
  filter(naam == "Gele Kwikstaart",
         wrntype > 0) %>%
  group_by(plotnaam, regio, periode_in_jaar, jaar) %>%
  summarise(aantal = sum(aantal),
            .groups = "drop")

# Add absences
gele_kwik_total <- design %>%
  left_join(gele_kwik_presences, 
            by = join_by(plotnaam, regio, periode_in_jaar, jaar)) %>%
  replace(is.na(.), 0) %>%
  arrange(plotnaam, periode_in_jaar, jaar)

# Add variables
gele_kwik_df <- gele_kwik_total %>%
  left_join(
    select(mas_data_df, plotnaam, regio, periode_in_jaar, jaar, status_teller,
    which(names(mas_data_df) == "n_predators"):length(names(mas_data_df))),
    by = join_by(plotnaam, regio, periode_in_jaar, jaar)) %>%
  distinct() %>%
  mutate(jaar.f = factor(jaar))
```

```{r}
# MCMC parameters
nchains <- 3           # number of chains
niter <- 4000          # number of iterations (incl. burn-in)
burnin <- niter / 2    # number of initial samples to discard (burn-in)
nparallel <- nchains   # number of cores used for parallel computing


brmpois1 <- brm(bf(aantal ~ periode_in_jaar + regio*jaar.f + (1 | plotnaam)), 
                data = gele_kwik_df, family = poisson(), 
                chains = nchains, warmup = burnin, iter = niter, 
                cores = nparallel, backend = "cmdstanr")
```

```{r}
summary(brmpois1)
```

```{r}
plot(brmpois1)
```

```{r}
pp_check(brmpois1, type = "bars_grouped", ndraws = 100, group = "regio",
         facet_args = list(ncol = 1, scales = "free_y"))
```


