---
title: "Data validatie 2023"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
renv::restore()

# Set up
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE)
opts_knit$set(root.dir = here::here())

Sys.setenv("PROJ_NETWORK" = "ON")

# Packages
library(tidyverse)
library(lubridate)
library(sf)

# Source
mbag_dir <- here()
data_path <- file.path("data", "mas")
```

# Inlezen data 2023

```{r}
file_geojson_2023 <- file.path(data_path, 
                               "20230802_qgis_export_sovon_wfs_2023.geojson")
mas_geojson_2023 <- read_sf(file_geojson_2023)
```

De CRS moet aangepast worden naar van Amersfoort naar Lambert 72. Dit doen we via een specifieke pipeline, zie: https://inbo.github.io/tutorials/tutorials/spatial_transform_crs_2/

```{r}
pipelines <- sf_proj_pipelines("EPSG:28992", "EPSG:31370")
glimpse(pipelines)

# We select the pipeline with lowest accuracy (< 0.02), by filtering on accuracy.
# If the grids are installed, this should match the first line of the pipelines object.

chosen_pipeline_definition <- pipelines %>%
  filter(accuracy < 0.02) %>% 
  pull(definition)

mas_31370_pipeline <- 
  st_transform(st_geometry(mas_geojson_2023), "EPSG:31370",
               pipeline = chosen_pipeline_definition) %>% 
  st_sf(st_drop_geometry(mas_geojson_2023), geometry = .) %>% 
  as_tibble() %>% 
  st_as_sf() %>%
  rename(x_amersfoord = x_coord,
         y_amersfoord = y_coord) %>%
  mutate(x_lambert = unlist(map(.data$geometry, 1)),
         y_lambert = unlist(map(.data$geometry, 2))) %>%
  select(oid:y_amersfoord, x_lambert, y_lambert, everything())
```

```{r}
source(here("src", "R", "wfs_wcs.R"))
vlaanderen <- get_feature_wfs(
  wfs = "https://eservices.minfin.fgov.be/arcgis/services/R2C/Regions/MapServer/WFSServer",
  layername = "regions",
  crs = "EPSG:31370",
  filter = "<Filter><PropertyIsEqualTo><PropertyName>regions:NameDUT</PropertyName><Literal>'Vlaams Gewest'</Literal></PropertyIsEqualTo></Filter>") %>%
  select(NameDUT)

ggplot() +
  geom_sf(data = vlaanderen) +
  geom_sf(data = mas_31370_pipeline, aes(colour = factor(maand)), size = 0.5) +
  theme(legend.position = "bottom") +
  labs(colour = "maand")
```

# 1) Binnen telperiodes

