---
title: "Inlezen MAS data"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#renv::restore()

# Set up
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE)
opts_knit$set(root.dir = here::here())

# Packages
library(tidyverse)

# Source
mbag_dir <- here()
data_path <- file.path("data", "mas")
```

# Controles

Eerst controleren we of `20220906_qgis_export_sovon_wfs.gpkg` en `20220906_qgis_export_sovon_wfs.geojson` dezelfde informatie bevatten.

File size `20220906_qgis_export_sovon_wfs.gpkg`:

```{r}
info <- file.info(file.path(data_path, "20220906_qgis_export_sovon_wfs.gpkg"))
info$size
```

File size `20220906_qgis_export_sovon_wfs.geojson`:

```{r}
info <- file.info(file.path(data_path, 
                            "20220906_qgis_export_sovon_wfs.geojson"))
info$size
```


