---
title: "Maak figuren voor rapport"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
renv::restore()

# Set up
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE)
opts_knit$set(root.dir = here::here())

# Packages
library(tidyverse)
library(INBOtheme)
library(gridExtra)

conflicted::conflicts_prefer(dplyr::filter)
theme_set(theme_inbo(transparent = TRUE))

# Source
dir.create("media", FALSE)
media_folder <- here("media")

source(here("src", "R", "plot_detection_curve.R"))
source(here("src", "R", "create_figures.R"))
```


# Distance sampling

```{r}
dir.create("media/distance", FALSE)
out_folder_distance <- here("media/distance")
dsmodel_path <- here("src/markdown/mas/distance_models")
beheermodel_path <- here("src/markdown/mas/analyses_cache")
```


## Per jaar

```{r}
dir.create("media/distance/per_jaar", FALSE)
dsmodels_per_jaar <- readRDS(here(dsmodel_path, "models_2018_2023.rds"))
```

### Densiteitschattingen

```{r}
for (spec in names(dsmodels_per_jaar)) {
  file <- paste0("densiteit_per_jaar_", tolower(spec), ".jpg")
  ds_model <- dsmodels_per_jaar[[spec]]
  p <- plot_densiteit(ds_model, spec, show_data = FALSE) +
    ggtitle("")
  
  ggsave(here(out_folder_distance, "per_jaar", file),
         p,
         dpi = 300,
         width = 8,
         height = 6)
}
```

### Detectiekans

```{r}
spec <- "Veldleeuwerik"
file <- paste0("detectiekans_per_jaar_simple_", tolower(spec), ".jpg")
ds_model <- dsmodels_per_jaar[[spec]]
p <- plot_detection_curve(ds_model)

ggsave(here(out_folder_distance, "per_jaar", file),
       p,
       dpi = 300,
       width = 8,
       height = 6)
```

```{r}
for (i in seq_along(dsmodels_per_jaar)) {
  spec <- names(dsmodels_per_jaar)[i]
  file <- paste0("detectiekans_per_jaar_", tolower(spec), ".jpg")
  ds_model <- dsmodels_per_jaar[[spec]] 
  variables <- names(ds_model$ddf$ds$aux$ddfobj$scale$parameters)
  
  if (any(grepl("regio", variables)) && any(grepl("jaar", variables))) {
    design_plot <- matrix(rep(0, 12 * 7), ncol = 7, byrow = TRUE)
    design_plot[, 1] <- 1
    design_plot[2, 2] <- 1
    design_plot[3, 3] <- 1
    design_plot[4, 4] <- 1
    design_plot[5, 5] <- 1
    design_plot[6, 6] <- 1
    design_plot[7, 7] <- 1
    design_plot[8:12, 2] <- 1
    design_plot[8, 3] <- 1
    design_plot[9, 4] <- 1
    design_plot[10, 5] <- 1
    design_plot[11, 6] <- 1
    design_plot[12, 7] <- 1
    
    labels_plot <- paste(c("De Moeren", "Oostelijke leemstreek", 
                           rep(c("De Moeren", "Oostelijke leemstreek"), each = 5)),
                         c(2018, 2018, rep(2019:2023, 2)), sep = " - ")
    
    mytheme <- theme(legend.position = "right")
  } else if (any(grepl("regio", variables))) {
    design_plot <- matrix(c(1, 0, 1, 1), ncol = 2, byrow = TRUE)
    labels_plot <- c("De Moeren", "Oostelijke leemstreek")
    mytheme <- theme()
  } else if (any(grepl("jaar", variables))) {
    labels_plot <- as.numeric(unique(ds_model$ddf$data$jaar))
    
    dim_design <- length(labels_plot)
    design_plot <- matrix(rep(1, dim_design), ncol = 1,
                          byrow = TRUE)
    design_plot <- cbind(design_plot, contr.treatment(dim_design))
    
    mytheme <- theme()
  } else {
    design_plot <- NULL
    labels_plot <- NULL
    mytheme <- theme()
  }
  palette <- colorRampPalette(RColorBrewer::brewer.pal(9,name = 'Set1'))(length(labels_plot))
  
  p <- plot_detection_curve(ds_model, design_mat = design_plot, 
                            labels = labels_plot) +
    scale_colour_manual(values = palette) +
    mytheme
  
  ggsave(here(out_folder_distance, "per_jaar", file),
         p,
         dpi = 300,
         width = 8,
         height = 6)
}
```

## Per stratum

```{r}
dir.create("media/distance/per_stratum", FALSE)
dsmodels_per_stratum2022 <- readRDS(here(dsmodel_path, "models_2022.rds"))
dsmodels_per_stratum2023 <- readRDS(here(dsmodel_path, "models_2023.rds"))
```

### Densiteitschattingen

```{r}
species <- sort(union(names(dsmodels_per_stratum2022),
                      names(dsmodels_per_stratum2023)))
for (spec in species) {
  file <- paste0("densiteit_per_stratum_", tolower(spec), ".jpg")
  ds_model2022 <- dsmodels_per_stratum2022[[spec]]
  ds_model2023 <- dsmodels_per_stratum2023[[spec]]
  
  if (is.null(ds_model2022)) {
    p <- plot_densiteit(ds_model2023, spec, show_data = FALSE,
                      year = 2023) +
      ggtitle("2023")
  } else if (is.null(ds_model2023)) {
    p <- plot_densiteit(ds_model2022, spec, show_data = FALSE,
                      year = 2022) +
      ggtitle("2022")
  } else {
    p <- plot_densiteit(ds_model2022, spec, show_data = FALSE,
                      year = 2022:2023,
                      dsmodel2 = ds_model2023) +
      ggtitle("") + 
      theme(plot.margin = unit(c(-8, 6, 6, 6), 
                                "pt"))
  }
  
  ggsave(here(out_folder_distance, "per_stratum", file),
         p,
         dpi = 300,
         width = 8,
         height = 6)
}
```

### Detectiekans

```{r}
for (spec in species) {
  file <- paste0("detectiekans_per_stratum_simple_", tolower(spec), ".jpg")
  ds_model2022 <- dsmodels_per_stratum2022[[spec]]
  ds_model2023 <- dsmodels_per_stratum2023[[spec]]
  
  if (is.null(ds_model2022)) {
    p <- plot_detection_curve(ds_model2023) +
      ggtitle("2023")
  } else if (is.null(ds_model2023)) {
    p <- plot_detection_curve(ds_model2022) +
      ggtitle("2022")
  } else {
    # 2022
    p1 <- plot_detection_curve(ds_model2022)
    
    # 2023
    p2 <- plot_detection_curve(ds_model2023)
    
    # adjust y-limits
    ymax_lim <- max(max(p1$plot_env$hist_df$counts),
                    max(p2$plot_env$hist_df$counts),
                    1)
    p1 <- p1 +
      scale_y_continuous(limits = c(0, ymax_lim),
                         breaks = seq(0, 100, by = 0.25)) +
      ggtitle("2022")
    p2 <- p2 +
      scale_y_continuous(limits = c(0, ymax_lim),
                         breaks = seq(0, 100, by = 0.25)) +
      labs(y = "") +
      ggtitle("2023")
    
    p <- grid.arrange(p1, p2, ncol = 2)
  }
  
  ggsave(here(out_folder_distance, "per_stratum", file),
         p,
         dpi = 300,
         width = 10,
         height = 6)
}
```


# Beheerovereenkomsten
## Oostelijke leemstreek

```{r}
dir.create("media/beheerovereenkomsten/oostelijke_leemstreek", FALSE)
mod_final_olpropsb_list <- readRDS(here(beheermodel_path,
                                        "mod_final_olpropsb_list.rds"))
```

```{r}
# get posterior draws for parameters of interest
draws_olpropsb_list <- lapply(mod_final_olpropsb_list, create_draws_df)
draws_olpropsb_list_wt <- lapply(mod_final_olpropsb_list,
                                 create_weighted_draws_df)
```

```{r}
min_threshold <- log(0.8)
max_threshold <- log(1.25)

area_prop_cats <- tibble(
  area_prop_sb_cat = c("nulbeleid", "laagbeleid", "middellaagbeleid",
                       "middelhoogbeleid", "hoogbeleid"),
  prop_area_sb = c("0", "<0.04", "0.04-0.07", "0.07-0.1", ">0.1")
  ) %>%
  rowid_to_column("order")

area_prop_cats2 <- tibble(
  area_prop_sb_cat = c("nulbeleid", "laagbeleid", "hoogbeleid"),
  prop_area_sb = c("0", "<0.07", ">0.07")
  ) %>%
  rowid_to_column("order")
```

```{r}
for (spec in names(draws_olpropsb_list)) {
  file <- paste0("beleidstoestand_fine_", tolower(spec), ".jpg")
  
  p <- draws_olpropsb_list[[spec]] %>%
    left_join(area_prop_cats, by = join_by(area_prop_sb_cat)) %>%
    mutate(label = paste0(area_prop_sb_cat, "\n(", prop_area_sb, ")"),
           label = reorder(label, order, decreasing = FALSE)) %>%
    ggplot(aes(x = label)) +
      geom_violin(aes(y = value_log, fill = trend_coarse),
                  colour = alpha("white", 0)) +
      geom_hline(yintercept = 0, linetype = "longdash", colour = "black") +
      geom_hline(yintercept = c(min_threshold, max_threshold),
                 linetype = "dotdash") +
      geom_errorbar(aes(ymin = lcl_log, ymax = ucl_log),
                    linewidth = 1, colour = "black", width = 0.1) +
      geom_point(aes(y = median_log),
                 size = 2.2, colour = "black") +
      scale_fill_manual(values =  c("chartreuse3",
                                    "gold",
                                    "firebrick1",
                                    "skyblue"),
                        drop = FALSE) +
      labs(y = "Procentueel verschil t.o.v. nulbeleid",
           x = "",
           fill = "Verschil") +
      scale_y_continuous(
        breaks = index_breaks(),
        labels = index_labels,
        minor_breaks = minor_breaks(),
        sec.axis = sec_axis(~ exp(.),
          breaks = index_breaks_rev(),
          labels = index_labels_rev(),
          name = "Relatief verschil t.o.v. nulbeleid")
        ) +
      theme(
        legend.position = "right",
        legend.background = element_rect(fill = "white", color = "darkgrey"),
        legend.margin = margin(6, 6, 6, 6)
        )
  
  ggsave(here("media", "beheerovereenkomsten", "oostelijke_leemstreek"
              , file),
         p,
         dpi = 300,
         width = 8,
         height = 6)
}
```

```{r}
for (spec in names(draws_olpropsb_list_wt)) {
  file <- paste0("beleidstoestand_coarse_", tolower(spec), ".jpg")
  
  p <- draws_olpropsb_list_wt[[spec]] %>%
    left_join(area_prop_cats2, by = join_by(area_prop_sb_cat)) %>%
    mutate(label = paste0(area_prop_sb_cat, "\n(", prop_area_sb, ")"),
           label = reorder(label, order, decreasing = FALSE)) %>%
    ggplot(aes(x = label)) +
      geom_violin(aes(y = value_log, fill = trend_coarse),
                  colour = alpha("white", 0)) +
      geom_hline(yintercept = 0, linetype = "longdash", colour = "black") +
      geom_hline(yintercept = c(min_threshold, max_threshold),
                 linetype = "dotdash") +
      geom_errorbar(aes(ymin = lcl_log, ymax = ucl_log),
                    linewidth = 1, colour = "black", width = 0.1) +
      geom_point(aes(y = median_log),
                 size = 2.2, colour = "black") +
      scale_fill_manual(values =  c("chartreuse3",
                                    "gold",
                                    "firebrick1",
                                    "skyblue"),
                        drop = FALSE) +
      labs(y = "Procentueel verschil t.o.v. nulbeleid",
           x = "",
           fill = "Verschil") +
      scale_y_continuous(
        breaks = index_breaks(),
        labels = index_labels,
        minor_breaks = minor_breaks(),
        sec.axis = sec_axis(~ exp(.),
          breaks = index_breaks_rev(),
          labels = index_labels_rev(),
          name = "Relatief verschil t.o.v. nulbeleid")
        ) +
      theme(
        legend.position = "right",
        legend.background = element_rect(fill = "white", color = "darkgrey"),
        legend.margin = margin(6, 6, 6, 6)
        )
  
  ggsave(here("media", "beheerovereenkomsten", "oostelijke_leemstreek"
              , file),
         p,
         dpi = 300,
         width = 8,
         height = 6)
}
```

