---
title: "Overzicht zandleemstreek"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
renv::restore()
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE)
opts_knit$set(root.dir = here::here())

library(tidyverse)
library(sf)
library(mapview)

mbag_dir <- here()
```

# Doel

Overzicht van de zandleemstreek geven om steekproefgebied af te bakenen.


# Kaartlagen

```{r}
landbouwstreken <- read_sf(here("data", "landbouwstreken", "Lbstrbel.shp")) %>%
  st_transform(crs = 31370)

akkervogelgebieden <- read_sf(here("data", "bo_vlm", 
                                   "akkervogelgebieden2022.shp")) %>%
  st_transform(crs = 31370)

vlaanderen <- read_sf("S:/Vlaanderen/Grenzen/Administratief/Vlaanderen.shp") %>%
  st_transform(crs = 31370)
```

```{r}
ggplot() +
  geom_sf(data = landbouwstreken, aes(fill = NAAM)) +
  geom_sf(data = akkervogelgebieden, fill = "black", colour = alpha("black", 0)) +
  geom_sf(data = vlaanderen, fill = alpha("black", 0), colour = "red", size = 1.5) +
  labs(fill = "Landbouwstreek")
```

# Selectie doelgebied

```{r}
zandleem_vlaanderen <- st_intersection(landbouwstreken, vlaanderen) %>%
  filter(NAAM == "Zandleemstreek")

akkervogelgebieden_zandleem <- st_intersection(akkervogelgebieden, 
                                               zandleem_vlaanderen)
```

```{r}
mapview(zandleem_vlaanderen, col.regions = "yellow") + mapview(akkervogelgebieden_zandleem)
```

