---
title: "MAS steekproefontwerp zandleemstreek"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
bibliography: mas.json
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# set up
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  out.width = "100%")
opts_knit$set(root.dir = here::here())

# packages
library(tidyverse)
library(targets)
library(sf)
library(mapview)

# globals
source(here("src", "R", "steekproefkader.R"))
source(here("src", "R", "wfs_wcs.R"))
targets_store <- here("src", "targets", "mas_steekproef_zavelberg", "_targets")
```

# Afbakening steekproefkader

## Perimeter bepalen

Intersectie landbouwstreek zandleemstreek in België met contour Vlaanderen. Nieuwe file geschreven "zandleemstreek_perimeters.gpkg" met enkel de zandleemstreek multipolygoon.

```{r, eval=FALSE}
# Code uitvoeren in mas_steekproef_zavelberg.Rproj
# na laden van globals in targets_steekproef_zavelberg.Rmd

library(sf)

# Lees in polygonen landbouwstreken
landbouwstreken <- read_sf(file.path(mbag_dir, "data", "landbouwstreken", 
                                     "Lbstrbel.shp")) |>
  st_transform(crs = 31370)

# Behoud Zandleemstreek
vlaanderen <- read_sf("S:/Vlaanderen/Grenzen/Administratief/Vlaanderen.shp") |>
  st_transform(crs = 31370)

zandleem_vlaanderen <- st_intersection(landbouwstreken, vlaanderen) |>
  filter(NAAM == "Zandleemstreek") |>
  mutate(section = NA) |>
  select(Naam = NAAM, section, geom = geometry)

st_write(obj = zandleem_vlaanderen,
         dsn = path_to_perimeters("zandleemstreek_perimeters.gpkg"))
```

In geel: prioritaire gebieden voor akkervogels.

```{r}
perimeters_data <- tar_read(perimeters_data, store = targets_store)
sbp_akkervogels <- tar_read(sbp_akkervogels, store = targets_store)

mapview(perimeters_data, color = "red", alpha.regions = 0) +
  mapview(sbp_akkervogels, col.regions = "yellow")
```

```{r}
binnen_sbp <- perimeters_data %>%
  st_intersection(sbp_akkervogels) %>%
  select(Naam) %>%
  mutate(opp = st_area(.),
         is_sbp = "binnen sbp")

buiten_sbp <- perimeters_data %>%
  st_difference(sbp_akkervogels %>%
                  st_union() %>%
                  st_combine()) %>%
  select(Naam) %>%
  mutate(opp = st_area(.),
         is_sbp = "buiten sbp")

opps <- bind_rows(buiten_sbp, binnen_sbp) %>% 
  st_drop_geometry()

opps %>%
  mutate(opp = units::set_units(opp, "ha")) %>%
  group_by(Naam) %>%
  mutate(opp_aandeel = opp / sum(opp)) %>%
  units::drop_units() %>%
  rename(opp_ha = opp) %>%
  relocate(is_sbp, .before = opp_ha) %>%
  arrange(Naam, is_sbp) %>%
  kable(digits = 2)
```


## Selectie openheid landschap

We selecteren OL en HOL binnen de perimeters.

```{r}
selectie_openheid_klasses <- tar_read(selectie_openheid_klasses, store = targets_store)
mapview(perimeters_data, color = "red", alpha.regions = 0) +
  mapview(selectie_openheid_klasses)
```
