---
title: "Verzameling verklarende variabelen"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
renv::restore()

# Set up
library(knitr)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE)
opts_knit$set(root.dir = here::here())

# Packages
library(tidyverse)
library(INBOtheme)
```

# Kadering

We willen een evaluatie van het effect van de maatregelen die getroffen worden binnen het agrarisch natuurbeleid op de trends en het voorkomen van akkervogels. Dit per soort, en op plotniveau (telcirkel).

Dit document geeft een overzicht van de verklarende variabelen die we gaan gebruiken in de modellen die we gaan fitten om bovenstaande te onderzoeken.

1. Welke variabelen?
2. Welk datatype (continu, categorisch, proporties, compositioneel ...)?
3. Waar verzameld?
4. Hoe verzameld?
5. Hoe berekend?
6. Verdere bedenkingen/opmerkingen. Zijn er bijvoorbeeld transformaties nodig?

# Respons variabele

Count data broedvogels (per soort), per telcirkel per telperiode

# Verklarende variabelen van prioritair belang

## Oppervlakte-aandeel beheerovereenkomsten

## Oppervlakte-aandeel hoofdteelten

## Diversiteit aan hoofdteelten


# Verklarende variabelen van secundair belang

## Regio

## Openheid landschap

## Soortbeschermingsplan

## Status teller

## Oppervlakte-aandeel kleine landschapselementen

## Oppervlakte-aandeel biolandbouw

## Perceelsgroottes

## X- en Y-coördinaten

## Inertie beheerovereenkomsten

## Aantal predatoren

## Jaar

## Telperiode
